In [2]:
import pandas as pd
from pandas import DataFrame as df
import csv

### 1. 감정 분류를 위한 대화 음성 데이터셋

In [106]:
# 파일 불러오기

df_4   = pd.read_csv('./4차년도.csv',encoding='cp949')
df_5   = pd.read_csv('./5차년도.csv',encoding='cp949')
df_5_2 = pd.read_csv('./5차년도_2차.csv',encoding='cp949')

In [107]:
# 모든 연도 데이터 합치기

merged_df = pd.concat([df_4, df_5, df_5_2])
merged_df = merged_df.reset_index()

In [108]:
# 필요 없는 column 삭제하기

data = merged_df.drop(columns=['index', 'wav_id', '나이', '성별', '상황'], axis=0)

In [109]:
data

,발화문,1번 감정,1번 감정세기,2번 감정,2번 감정세기,3번 감정,3번 감정세기,4번 감정,4번감정세기,5번 감정,5번 감정세기
0,"어, 청소 니가 대신 해 줘!",Neutral,0,Angry,1,Neutral,0,Neutral,0,Angry,1
1,둘 다 청소 하기 싫어. 귀찮아.,Neutral,0,Angry,1,Neutral,0,Neutral,0,Angry,1
2,둘 다 하기 싫어서 화내.,Angry,1,Angry,1,Neutral,0,Angry,1,Angry,1
3,그럼 방세는 어떡해.,Sadness,1,Sadness,1,Sadness,1,Sadness,1,Sadness,1
4,권태긴줄 알았는데 다른 사람이 생겼나보더라고.,Sadness,1,Sadness,1,Sadness,1,Sadness,2,Sadness,1
...,...,...,...,...,...,...,...,...,...,...,...
43986,나 엘리베이터에 갇혔어.,happiness,1,sadness,1,sadness,2,sadness,1,sadness,1
43987,하지만 기분이 나쁜 걸 어떡해?,sadness,1,fear,1,sadness,2,sadness,1,neutral,0
43988,자취방 엘리베이턴데 정전인가봐.,sadness,1,neutral,0,sadness,2,fear,1,sadness,1
43989,나 드디어 프로젝트 끝났어!,disgust,1,sadness,1,neutral,0,happiness,1,sadness,1
43990,걱정해줘서 고마워.,neutral,0,neutral,0,neutral,0,neutral,0,neutral,0

In [110]:
# 통합된 하나의 감정 추출하기

emotion_dict = {'happy': 0, 'angry': 1, 'disgust': 2, 'fear': 3, 'neutral': 4, 'sad': 5, 'surprise': 6}
emotion_list = ['happiness', 'angry', 'disgust', 'fear', 'neutral', 'sadness', 'surprise']
emotions = [] # [happy, angry, disgust, fear, neutral, sad, surprise]

for i in range(len(data)):
    emotions = [0 for _ in range(7)]
    
    for j in range(1, 10, 2):
        emotions[emotion_list.index(data.iloc[i, j].lower())] += 1
    
#     data.loc[i, '평균감정'] = emotion_list[emotions.index(max(emotions))] # 글자로
    data.loc[i, '평균감정'] = emotions.index(max(emotions)) # 숫자로

In [111]:
data

,발화문,1번 감정,1번 감정세기,2번 감정,2번 감정세기,3번 감정,3번 감정세기,4번 감정,4번감정세기,5번 감정,5번 감정세기,평균감정
0,"어, 청소 니가 대신 해 줘!",Neutral,0,Angry,1,Neutral,0,Neutral,0,Angry,1,4.0
1,둘 다 청소 하기 싫어. 귀찮아.,Neutral,0,Angry,1,Neutral,0,Neutral,0,Angry,1,4.0
2,둘 다 하기 싫어서 화내.,Angry,1,Angry,1,Neutral,0,Angry,1,Angry,1,1.0
3,그럼 방세는 어떡해.,Sadness,1,Sadness,1,Sadness,1,Sadness,1,Sadness,1,5.0
4,권태긴줄 알았는데 다른 사람이 생겼나보더라고.,Sadness,1,Sadness,1,Sadness,1,Sadness,2,Sadness,1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
43986,나 엘리베이터에 갇혔어.,happiness,1,sadness,1,sadness,2,sadness,1,sadness,1,5.0
43987,하지만 기분이 나쁜 걸 어떡해?,sadness,1,fear,1,sadness,2,sadness,1,neutral,0,5.0
43988,자취방 엘리베이턴데 정전인가봐.,sadness,1,neutral,0,sadness,2,fear,1,sadness,1,5.0
43989,나 드디어 프로젝트 끝났어!,disgust,1,sadness,1,neutral,0,happiness,1,sadness,1,5.0
43990,걱정해줘서 고마워.,neutral,0,neutral,0,neutral,0,neutral,0,neutral,0,4.0

In [112]:
# 필요 없는 column 삭제하기

data = data.drop(columns=['1번 감정', '1번 감정세기', '2번 감정', '2번 감정세기', '3번 감정', '3번 감정세기', '4번 감정', '4번감정세기', '5번 감정', '5번 감정세기'], axis=0)
data

                             발화문  평균감정
0               어, 청소 니가 대신 해 줘!   4.0
1             둘 다 청소 하기 싫어. 귀찮아.   4.0
2                 둘 다 하기 싫어서 화내.   1.0
3                    그럼 방세는 어떡해.   5.0
4      권태긴줄 알았는데 다른 사람이 생겼나보더라고.   5.0
...                          ...   ...
43986              나 엘리베이터에 갇혔어.   5.0
43987          하지만 기분이 나쁜 걸 어떡해?   5.0
43988          자취방 엘리베이턴데 정전인가봐.   5.0
43989            나 드디어 프로젝트 끝났어!   5.0
43990                 걱정해줘서 고마워.   4.0

[43991 rows x 2 columns]

In [116]:
# 데이터 저장

path = './processed_data'
data.to_csv(path , sep=',' , header=None , index=None)

In [115]:
data

                             발화문  평균감정
0               어, 청소 니가 대신 해 줘!   4.0
1             둘 다 청소 하기 싫어. 귀찮아.   4.0
2                 둘 다 하기 싫어서 화내.   1.0
3                    그럼 방세는 어떡해.   5.0
4      권태긴줄 알았는데 다른 사람이 생겼나보더라고.   5.0
...                          ...   ...
43986              나 엘리베이터에 갇혔어.   5.0
43987          하지만 기분이 나쁜 걸 어떡해?   5.0
43988          자취방 엘리베이턴데 정전인가봐.   5.0
43989            나 드디어 프로젝트 끝났어!   5.0
43990                 걱정해줘서 고마워.   4.0

[43991 rows x 2 columns]

### 한국어 감정 정보가 포함된 단발성 대화 데이터셋

In [4]:
# 데이터 불러오기

df_short = pd.read_csv('./한국어_단발성_대화_데이터셋.csv')

In [5]:
df_short

                                                Sentence Emotion
0                               언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                           그냥 내 느낌일뿐겠지?      공포
2                                         아직너무초기라서 그런거죠?      공포
3                                          유치원버스 사고 낫다던데      공포
4                                            근데 원래이런거맞나요      공포
...                                                  ...     ...
38589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..      혐오
38590                                        재미가 없으니 망하지      혐오
38591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...      혐오
38592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ      혐오
38593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요      혐오

[38594 rows x 2 columns]

In [ ]:
# 감정 데이터 숫자로 변환하기

emotion_dict = {'happy': 0, 'angry': 1, 'disgust': 2, 'fear': 3, 'neutral': 4, 'sad': 5, 'surprise': 6}
emotion_list = ['happiness', 'angry', 'disgust', 'fear', 'neutral', 'sadness', 'surprise']
emotions = [] # [happy, angry, disgust, fear, neutral, sad, surprise]

for i in range(len(data)):
    emotions = [0 for _ in range(7)]
    
    for j in range(1, 10, 2):
        emotions[emotion_list.index(data.iloc[i, j].lower())] += 1
    
#     data.loc[i, '평균감정'] = emotion_list[emotions.index(max(emotions))] # 글자로
    data.loc[i, '평균감정'] = emotions.index(max(emotions)) # 숫자로